#TODO: Replace spring.datasource.* after contenerization
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://host.docker.internal:16832/payments_mcsv
    username: postgres
    password: root
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: guest
    username: guest