#TODO: Replace spring.datasource.* after contenerization
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/RSWW_175782_customers
    username: postgres
    password: student