version: '3.4'

services:
  tour-operator:
    container_name: tour-operator
    image: tour-operator
    restart: always
    build:
      context: ./TourOperator
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_HTTPS_PORT: https://+:443
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:80
      - 5001:443
    # networks:
    #   back:
    #   front:

  payment-service:
    image: pg-travel-payment-service
    build: ./payments
    container_name: payment-service
    ports:
      - 8081:8080

  customer-service:
    image: pg-travel-customer-service
    build: ./customers
    container_name: customer-service
    ports:
      - 8082:8080

  offer-service:
    container_name: offer-service
    image: offer-service
    restart: always
    build:
      context: ./services
      dockerfile: Dockerfile.Offer
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_HTTPS_PORT: https://+:443
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8083:80
      - 5003:443
    # networks:
    #   back:
    #   front:
    depends_on:
      - tour-operator

  order-service:
    container_name: order-service
    image: order-service
    restart: always
    build:
      context: ./services
      dockerfile: Dockerfile.Order
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_HTTPS_PORT: https://+:443
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8084:80
      - 5005:443
    # networks:
    #   back:
    #   front:
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    # networks:
    #   back:
    #   front:
  
  frontend:
    image: pg-travel-front-server
    container_name: front-server
    build: ./frontend
    restart: always
    ports:
      - 8099:8080


# networks:
#   back:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#       - subnet: "172.18.0.0/24"
#         gateway: 172.18.0.1
#   front:
#     driver: bridge