version: '3.4'

services:
  touroperator:
    image: tour-operator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_HTTPS_PORT: https://+:443
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5000:80
      - 5001:443